modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL=""
license="MIT"
[[mods]]
    modId="catbopthings"
    version="${file.jarVersion}"
    displayName="CATBOP Things"
    description='''
    A mod for Create And Tinkers Building Oriented Pack
    '''
[[dependencies.catbopthings]]
    modId="forge"
    mandatory=true
    versionRange="[46.0.0,)"
    ordering="NONE"
    side="BOTH"
#[[dependencies.catbopthings]]
#    modId="tconstruct"
#    mandatory=true
#    versionRange="[3.6.3.111,)"
#    ordering="AFTER"
#    side="BOTH"
[[dependencies.catbopthings]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.8.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.catbopthings]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1,)"
    ordering="NONE"
    side="BOTH"
